[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"

[[headers]]
  for = "/:lang*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[redirects]]
  from = "/"
  to = "/ru"
  status = 301
  force = true

